### ISSUE TITLE
Suggestion: globally maintained address book

### ISSUE THREAD

**Issue by tomdickharryeth** [zer0-os/zChain#42]
Hello, more of a usability suggestion, initially raised by Joe's Time Machines#5690

Currently we need to update our local address book with peerID and a name, for each person. This means everyone needs to post their peerID and name and everyone has to update these manually locally. It would be nice to have a globally maintained address book somehow, for those that wish to associate their peerid with a name.

**Comment by ratik21** [comment]
Hi @tomdickharryeth, thanks for the suggestion.

We were initially thinking to have a global address book only :: a peer can set his own name which would be visible to others. But the issue with that design is that names can never be unique, so eventually when the system scales up, you can have a lot of peers with the same name.

Which is why, for now, we have kept it local.

**Comment by tomdickharryeth** [comment]
> Hi @tomdickharryeth, thanks for the suggestion.
> 
> We were initially thinking to have a global address book only :: a peer can set his own name which would be visible to others. But the issue with that design is that names can never be unique, so eventually when the system scales up, you can have a lot of peers with the same name.
> 
> Which is why, for now, we have kept it local.

Makes sense thanks!
